
evaluating_word_salad:
  description: |
    指定されたカクヨム作品({work_id}) の一つのエピソードID: {episode_id} から小説コンテンツを取得し、その文章が文意の汲み取れない読みにくい文章（ワードサラダ）になっていないかを評価してください。
    
    まず、利用可能なツールを使用してカクヨムURLから小説コンテンツを直接取得してください。
    その後、以下の軸からエピソードを評価してください：
    - 全体がまとめて意味不明な文章かどうか
    - 読み手にとって理解不能な表現が含まれている
    - 文章の流れが不自然であるかどうか
    
    読んだ後、あなたは最終的な判断を行い、以下のいずれかで評価してください：
    - 問題なし
    - 要注意
    - 文章破綻
  
    また、何か問題がある場合は、その理由を簡潔に説明してください。

  agent: word_salad_reviewer

  expected_output:
    EpisodeVerdict スキーマで返すこと。
